name: "publish github pages"

on:
  workflow_dispatch:
  push:
    branches:
    - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: yarn

    # - name: Run tests
    #   run: npm run test:headless

    - name: Build
      run: yarn run build:github

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/talight-desktop
        enable_jekyll: true
